### ISSUE TITLE
minIO configuration does not yet support envisioned workflow

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#114]
The current minIO configuration, as implemented in staging environment, is not suitable for supporting the envisioned workflow because the minIO buckets generated by `dominode-bootstrapper` are not being mounted in the GeoServer pod. As such it is currently not possible to expose uploaded raster data via GeoServer

The plan is to use minIO-backed storage to store raster datasets and then have them be available to GeoServer. The image below depicts this:

![dominode_raster_workflows3](https://user-images.githubusercontent.com/732010/94941853-6852dd80-04cd-11eb-8845-b726c821295f.png)

- We need to mount the minIO root directory as the `data` dir inside the GeoServer datadir - i.e. in `{geoserver-data-dir}/data`
- When a user uses GeoServer to setup a new raster layer, he shall be able to navigate through the minIO buckets inside `geoserver-data-dir/data` and select the relevant raster file(s)
- As depicted in the above drawing, the root of minIO shall be mounted inside `{geoserver-data-dir}/data`. This means that the other geoserver configuration files and dirs which are normally inside `{geoserver-data-dir}` shall not be exposed by minIO.

Acceptance criteria for considering this issue solved:

- User with appropriate access permissions is able to use the minIO web UI to upload a geotiff file to the `dominode_staging/ppd` bucket
- User with appropriate access permissions is able to use GeoServer UI to add a new geotiff raster store pointing to the uploaded file and the file is successfully served by GeoServer as via WMS.

**Comment by lucernae** [comment]
> As depicted in the above drawing, the root of minIO shall be mounted inside {geoserver-data-dir}/data. This means that the other geoserver configuration files and dirs which are normally inside {geoserver-data-dir} shall not be exposed by minIO.

I would assume that you also don't want the media dir to be exposed via minio?

**Comment by lucernae** [comment]
Changes:
- Mount root directory of minio to /spcgeonode-geodatadir/data per requested
- Move out geoserver-data-dir and media bucket as a different NFS share

Question:
- There needs to be a mechanism to specify that the bucket is writable by GeoServer. For now I did this by manually `chmod a+w` every bucket in the minio share, so that GeoServer can import the files inside the bucket. If it's not possible to do this from the bootstrapper, it has to be done from scripts in helm.
- How do you implement this?
> User with appropriate access permissions is able to use GeoServer UI to add a new geotiff raster store pointing to the uploaded file and the file is successfully served by GeoServer as via WMS.

Currently anyone with access to the GeoServer UI will be able to browse all content inside `data/` directory.

Tests:
- I uploaded mmi_1.tif in ppd bucket. I don't have ppd credentials, so I use superuser accessKey.

![image](https://user-images.githubusercontent.com/831865/94976682-e9e35380-053f-11eb-8e2e-354159242dda.png)

- Import it from GeoServer UI

![image](https://user-images.githubusercontent.com/831865/94976713-0089aa80-0540-11eb-8066-3437f1b70ee7.png)

- Preview it via WMS

https://stage.dominode.piensa.co/geoserver/ppd/wms?service=WMS&version=1.1.0&request=GetMap&layers=ppd%3Ammi_1&bbox=80.171%2C12.9017%2C80.30000000000001%2C13.1897&width=344&height=768&srs=EPSG%3A4326&access_token=UuqpJqu70IxZUMWmgf2CuipA4O32ZZ&format=application/openlayers

Let me know if it can handles big files or not (couple of MBs uploaded from minio instance).

**Comment by ricardogsilva** [comment]
> > As depicted in the above drawing, the root of minIO shall be mounted inside {geoserver-data-dir}/data. This means that the other geoserver configuration files and dirs which are normally inside {geoserver-data-dir} shall not be exposed by minIO.
> 
> I would assume that you also don't want the media dir to be exposed via minio?

yes, that is correct. The GeoNode media dir does not need to be exposed via minIO.

**Comment by ricardogsilva** [comment]
@lucernae please do not re-assign task back to me (surprised me a bit when searching for it) - leave it assigned to you, even when I'm supopsed to be reviewing it - ultimately the assignee is the person that is oding the actual work.

**Comment by ricardogsilva** [comment]
> There needs to be a mechanism to specify that the bucket is writable by GeoServer. For now I did this by manually chmod a+w every bucket in the minio share, so that GeoServer can import the files inside the bucket. If it's not possible to do this from the bootstrapper, it has to be done from scripts in helm.

I'm not sure I understand this - please provide a more thorough description.

I would imagine that our configuration needs to make sure the user used by GeoServer to access the NFS mount of its `{data-dir}/data` directory allows it r+w access to that dir and whatever subdirs and files that may be contained inside of it. Seems like a unix permissions problem to me.

AFAIK minIO does not allow any kind of [configuration](https://docs.min.io/docs/minio-server-configuration-guide.html) of the filesystem that it uses. It only allows us to configure how users access buckets and objects via itself.

**Comment by lucernae** [comment]
> I'm not sure I understand this - please provide a more thorough description.

Geoserver write something inside the bucket when the bucket is mounted (as NFS mount).
Minio and GeoServer mounts these as different user.
IMHO, forcing Minio and GeoServer to use as the same user is too strict.

Basically I want to know how you would like to implement it given these constraint:
- GeoServer UI will be able to see any folder mounted on `data/` regardless of the MinIO user permissions. These buckets has to be owned (in a Unix fs - sense) by GeoServer. Is this going to be a problem for you? (department A might import layers uploaded via minio by department B).
- Since you create the bucket from bootstrapper do you want to set this permission from the bootstrapper?
- If not, then there should be scripts in the helm charts that bootstrap permission checks of the `data/` directory. It will assume permission for all the buckets inside MinIO.

**Comment by ricardogsilva** [comment]
> GeoServer UI will be able to see any folder mounted on data/ regardless of the MinIO user permissions. These buckets has to be owned (in a Unix fs - sense) by GeoServer. Is this going to be a problem for you? (department A might import layers uploaded via minio by department B).

Yes, this is problematic but I don't see an elegant alternative. Ideally we would like to have total access isolation of data from different departments. However, I don't see how that is possible with the current tech stack that we have. AFAIK GeoServer has direct access to the filesystem, and uses a single OS user for all filesystem-related operations. This means that there seems to be no way to make some GeoServer workspace only have access to a set of filesystem-paths. It is not ideal, but I think it will have to do.


> IMHO, forcing Minio and GeoServer to use as the same user is too strict.

But aren't they already using the same UID? Looking at [geoserver dockerfile] and [minio dockerfile] they both seem to be running as `root` (which is actually a bad practice, but that is a war to fight some other day), so I would think they already have the same UID and thus GeoServer should have RW access to the buckets and its contents. Or is this related to the NFS mount? 

> If not, then there should be scripts in the helm charts that bootstrap permission checks of the data/ directory. It will assume permission for all the buckets inside MinIO.

Yeah, I would prefer if the bootstrapper were to focus only on bootstrapping the apps and did not have to focus on infrastructure for them.


[geoserver dockerfile]: https://github.com/dominodeorg/dominode/blob/master/geonode_dominode/scripts/spcgeonode/geoserver/Dockerfile
[minio dockerfile]: https://hub.docker.com/r/minio/minio/dockerfile

**Comment by lucernae** [comment]
> AFAIK GeoServer has direct access to the filesystem, and uses a single OS user for all filesystem-related operations

Yes, owned by user who runs the tomcat server. So we don't need to change anything regarding this in this case.



>> IMHO, forcing Minio and GeoServer to use as the same user is too strict.
>
> But aren't they already using the same UID? Looking at geoserver dockerfile and minio dockerfile they both seem to be running as root

The Dockerfile does built by root, but you can change runtime user into a different user. MinIO currently not running as root so GeoServer thinks it is a different user (not root). I also don't know why it can't write the file even if the jvm runs as root already. Probably because I mounted the NFS share as `nobody` group. I ended up having to explicitly give `a+w ` permission for the directory. After that GeoServer is able to put a lockfile (with ownership nobody:nobody) when importing the layer.

So, between making both run as the same user vs giving a+w NFS folder permission, which one would you prefer?
I personally leaning towards a+w NFS folder for the bucket, because the only process capable of using the NFS folder is the pod itself. User still uploads to/see bucket with permission given by MinIO.

**Comment by ricardogsilva** [comment]
> So, between making both run as the same user vs giving a+w NFS folder permission, which one would you prefer?
I personally leaning towards a+w NFS folder for the bucket, because the only process capable of using the NFS folder is the pod itself. User still uploads to/see bucket with permission given by MinIO.

:+1: from me, since you already tried it and it seems to work OK

If I understand correctly, this is something you are able to do as a one time setup, on the NFS server, so it is something which does not complicate pod rescheduling, right?

**Comment by ricardogsilva** [comment]
I'll go ahead and merge #115 then
