### ISSUE TITLE
Create dedicated helm chart for the project

### ISSUE THREAD

**Issue by ricardogsilva** [dominodeorg/dominode#78]
Create a dedicated helm chart for deploying the various pieces of this project into a k8s cluster. For the moment we need this chart to contain GeoNode and the dominode-bootstrapper image created in #74.

It is likely that the CORS app (#10) shall also be developed as an additional service to be integrated into this chart at some point in the future

**Comment by lucernae** [comment]
I assume you just want to create the template in this repo? Do you want to store the deployment parameter in other repo somewhere or just store them in Rancher?

**Comment by lucernae** [comment]
> Can you be a bit more specific on what you mean by deployment parameter?

Deployment parameter --> values that you pass to helm (like the postgres password, db location, etc)
It can be via `values.yml` (a file) or the value of the option itself (like `minioHost: http://myminio.io/`)

But I do recommend it as a file though (`values.yml`) we might have two files which is for staging and production. Or also local cluster if you want. The local cluster parameter can be stored here. But staging and prod might have sensitive secrets inside and this repository is public.

> If you mean config maps, I'd like to have them on this repo as well. But perhaps I am misunderstanding.

It may have a config map in the future, depending on the service itself. It will be stored here as a template with the value placeholder.

> Ultimate goal is to be able to deploy this new chart with rancher, but also be able to deploy it locally by some combination of CLI commands (so bypassing rancher)

AFAIK, and I might be not knowledgeable enough for this one. We can deploy via helm or rancher but not both since one deployment method will track the history. I prefer to do it via rancher though if you ask me. However when testing charts in a sandbox environment, I used helm directly since it's easily scriptable. 

At the moment I don't know how Helm track it's history, hopefully in a configmap somewhere in the cluster. But I know that Rancher also track the chart version so we can rollback to previous version. (but I guess this doesn't matter, if we deploy via helm using local folder we can choose version too).

Maybe I should look into it a bit to see if we can use both together.

**Comment by ricardogsilva** [comment]
> We can deploy via helm or rancher but not both since one deployment method will track the history

What I mean is just for local dev it probably isn't necessary to use rancher - it can be left up to the discretion of each dev. I don't think we need a way to mix both rancher and non-rancher deployment on the same cluster, this is purely for setting up a local dev env.

**Comment by lucernae** [comment]
Okay, you mentioned Rancher so I thought this is for staging/production deployment.
For local dev cluster, sure we can use helm. That means we don't need to store the deployment parameter here if I understand it correctly (the values.yaml for staging and prod).

**Comment by ricardogsilva** [comment]
Done as of 9dd6ac28eb7e69ccbc5ab1a13e9d4c44790f00c5
